version: "3"

services:
  localhost:
    image: postgres:12.4
    volumes:
      - posgres_data:/var/lib/postgresql/data

  django_app:
    build: .
    volumes:
      - static:/code/static
      - .:/code
    depends_on:
      - localhost

  nginx:
    image: nginx:1.17
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/cinf.d
      - static:/code/static
    depends_on:
      - django_app

volumes:
  .:
  posgres_data:
  static:

